/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-container': '#39b8fd',
        'surface-container-highest': '#e4e1ee',
        'surface-container': '#f0ecf9',
        'primary-container': '#4f46e5',
        'surface-container-lowest': '#ffffff',
        tertiary: '#7e3000',
        border: '#E5E7EB',
        'on-surface-variant': '#464555',
        'on-primary-fixed': '#0f0069',
        'tertiary-fixed-dim': '#ffb695',
        'surface-bright': '#fcf8ff',
        'on-error-container': '#93000a',
        'secondary-fixed-dim': '#89ceff',
        'on-secondary-fixed': '#001e2f',
        'on-tertiary': '#ffffff',
        secondary: '#006591',
        'surface-tint': '#4d44e3',
        'on-tertiary-container': '#ffd2be',
        'primary-fixed-dim': '#c3c0ff',
        'primary-fixed': '#e2dfff',
        error: '#EF4444',
        'surface-container-high': '#eae6f4',
        'text-muted': '#6B7280',
        'on-primary': '#ffffff',
        success: '#10B981',
        'inverse-primary': '#c3c0ff',
        'tertiary-container': '#a44100',
        outline: '#777587',
        'inverse-on-surface': '#f3effc',
        'on-error': '#ffffff',
        'surface-container-low': '#f5f2ff',
        'surface-dim': '#dcd8e5',
        'secondary-fixed': '#c9e6ff',
        'on-secondary': '#ffffff',
        surface: '#FFFFFF',
        background: '#F9FAFB',
        'inverse-surface': '#302f39',
        'on-surface': '#1b1b24',
        'error-container': '#ffdad6',
        'outline-variant': '#c7c4d8',
        'surface-variant': '#e4e1ee',
        'on-secondary-fixed-variant': '#004c6e',
        'on-tertiary-fixed-variant': '#7b2f00',
        'text-primary': '#111827',
        'on-background': '#1b1b24',
        'on-primary-container': '#dad7ff',
        'on-secondary-container': '#004666',
        'on-tertiary-fixed': '#351000',
        'tertiary-fixed': '#ffdbcc',
        primary: '#3525cd',
        'on-primary-fixed-variant': '#3323cc',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-md': '16px',
        'stack-lg': '32px',
        'container-max': '1280px',
        'stack-sm': '8px',
        gutter: '24px',
        'margin-desktop': '40px',
      },
      fontFamily: {
        'body-md': ['Inter'],
        code: ['JetBrains Mono'],
        'label-md': ['Inter'],
        'headline-lg': ['Inter'],
        'headline-sm': ['Inter'],
        'headline-md': ['Inter'],
        'body-lg': ['Inter'],
        'label-sm': ['Inter'],
      },
      fontSize: {
        'body-md': ['15px', { lineHeight: '1.5', fontWeight: '400' }],
        code: ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.4', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      boxShadow: {
        soft: '0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03)',
        hover: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
